packageExtensions:
  "@envelop/core@*":
    peerDependencies:
      tslib: "*"
  "@envelop/parser-cache@*":
    peerDependencies:
      tslib: "*"
  "@envelop/types@*":
    peerDependencies:
      tslib: "*"
  "@envelop/validation-cache@*":
    peerDependencies:
      tslib: "*"
  "@mantine/styles@*":
    dependencies:
      "@emotion/cache": "*"
      "@emotion/react": "*"
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  "@n1ru4l/graphql-live-query@*":
    dependencies:
      tslib: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  vite@*:
    dependencies:
      supports-color: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.2.cjs
