yarnPath: .yarn/releases/yarn-3.2.2.cjs

pnpFallbackMode: all
pnpMode: loose

packageExtensions:
  '@envelop/core@*':
    peerDependencies:
      tslib: '*'
  '@envelop/types@*':
    peerDependencies:
      tslib: '*'
  '@envelop/validation-cache@*':
    peerDependencies:
      tslib: '*'
  '@envelop/parser-cache@*':
    peerDependencies:
      tslib: '*'
  '@n1ru4l/graphql-live-query@*':
    dependencies:
      tslib: '*'
  'node-fetch@*':
    dependencies:
      encoding: '*'
  '@mantine/styles@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/cache': '*'
      '@emotion/serialize': '*'
      '@emotion/utils': '*'
  'vite@*':
    dependencies:
      'supports-color': '*'
  'debug@*':
    dependencies:
      'supports-color': '*'
